<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<PreserveCompilationReferences>true</PreserveCompilationReferences>
		<DisableAppDomain>true</DisableAppDomain>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<Content Include="..\..\src\RulesetEngine.API\bin\$(Configuration)\$(TargetFramework)\RulesetEngine.API.deps.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>testhost.deps.json</Link>
		</Content>
		<Content Include="appsettings.Development.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="appsettings.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="..\..\src\RulesetEngine.API\bin\Debug\net9.0\RulesetEngine.API.deps.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\RulesetEngine.API\RulesetEngine.API.csproj" />
		<ProjectReference Include="..\..\src\RulesetEngine.Application\RulesetEngine.Application.csproj" />
		<ProjectReference Include="..\..\src\RulesetEngine.Domain\RulesetEngine.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>

